import { useState } from 'react';

export default function App() {
  const [city, setCity] = useState('Bengaluru');
  const [weather, setWeather] = useState(null);
  const search = async () => { const response = await fetch(`/api/weather?city=${encodeURIComponent(city)}`); setWeather(await response.json()); };
  return <main><style>{css}</style><nav><b>weather / now</b><span>OpenWeather powered</span></nav><section className="hero"><p className="eyebrow">FOUNDATIONAL PROJECT 01</p><h1>Read the sky<br /><i>before you move.</i></h1><p className="lede">A focused weather dashboard built around one useful question: what does today feel like?</p><div className="search"><input value={city} onChange={event => setCity(event.target.value)} onKeyDown={event => event.key === 'Enter' && search()} /><button onClick={search}>Check weather</button></div>{weather && <article className="weather"><strong>{weather.city}</strong><span>{weather.temperature ?? weather.main?.temp}°</span><small>{weather.condition ?? weather.weather?.[0]?.description}</small></article>}</section></main>;
}
const css = `*{box-sizing:border-box}body{margin:0;background:#e8f0ed;color:#173c38;font:16px Georgia,serif}main{min-height:100vh}nav{display:flex;justify-content:space-between;padding:28px 7%;font:12px Arial,sans-serif;letter-spacing:.08em;text-transform:uppercase}.hero{max-width:900px;margin:10vh auto;padding:0 7%}.eyebrow{color:#e26d4f;font:12px Arial,sans-serif;letter-spacing:.18em}h1{font-size:clamp(52px,9vw,112px);line-height:.9;font-weight:400;margin:24px 0}.hero i{color:#e26d4f}.lede{max-width:420px;line-height:1.6}.search{display:flex;max-width:560px;margin-top:42px;border-bottom:2px solid #173c38}.search input{background:none;border:0;flex:1;padding:16px 0;font:24px Georgia;color:#173c38}.search button{border:0;background:#173c38;color:white;padding:0 22px}.weather{margin-top:34px;display:grid;grid-template-columns:1fr auto;gap:8px;background:#f8f5ec;padding:24px;max-width:560px}.weather span{font-size:58px;grid-row:span 2}.weather small{color:#e26d4f}@media(max-width:600px){nav span{display:none}.search{display:block;border:0}.search input,.search button{width:100%;padding:16px;border:1px solid #173c38}.search button{margin-top:8px}}
`;
